// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIs.Hospital.CleanCrud.DAL;

#nullable disable

namespace WebAPIs.Hospital.CleanCrud.DAL.Migrations
{
    [DbContext(typeof(HospitalContext))]
    partial class HospitalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiseasePatient", b =>
                {
                    b.Property<int>("DiseasesID")
                        .HasColumnType("int");

                    b.Property<int>("PatientsID")
                        .HasColumnType("int");

                    b.HasKey("DiseasesID", "PatientsID");

                    b.HasIndex("PatientsID");

                    b.ToTable("DiseasePatient");
                });

            modelBuilder.Entity("WebAPIs.Hospital.CleanCrud.DAL.Disease", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Disease");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Diabetes"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Hypertension"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Asthma"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Depression"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Arthritis"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Allergy"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Flu"
                        });
                });

            modelBuilder.Entity("WebAPIs.Hospital.CleanCrud.DAL.Doctor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformanceRate")
                        .HasColumnType("int");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Jessie",
                            PerformanceRate = 65,
                            Salary = 27064f,
                            Speciality = "Hematology"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Judy",
                            PerformanceRate = 32,
                            Salary = 18711f,
                            Speciality = "Neurology"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Naomi",
                            PerformanceRate = 27,
                            Salary = 32145f,
                            Speciality = "Pediatrics"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Joann",
                            PerformanceRate = 72,
                            Salary = 9232f,
                            Speciality = "Hematology"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Judy",
                            PerformanceRate = 19,
                            Salary = 48498f,
                            Speciality = "Dermatology"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Alyssa",
                            PerformanceRate = 79,
                            Salary = 16586f,
                            Speciality = "Gastroenterology"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Mable",
                            PerformanceRate = 5,
                            Salary = 33706f,
                            Speciality = "Infectious Disease"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Paula",
                            PerformanceRate = 0,
                            Salary = 19094f,
                            Speciality = "Urology"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Rafael",
                            PerformanceRate = 97,
                            Salary = 12266f,
                            Speciality = "Pediatrics"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Sara",
                            PerformanceRate = 82,
                            Salary = 45041f,
                            Speciality = "Pediatrics"
                        });
                });

            modelBuilder.Entity("WebAPIs.Hospital.CleanCrud.DAL.Patient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DoctorID");

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DoctorID = 5,
                            Name = "Dana"
                        },
                        new
                        {
                            ID = 2,
                            DoctorID = 7,
                            Name = "Isaac"
                        },
                        new
                        {
                            ID = 3,
                            DoctorID = 9,
                            Name = "Damon"
                        },
                        new
                        {
                            ID = 4,
                            DoctorID = 8,
                            Name = "Miriam"
                        },
                        new
                        {
                            ID = 5,
                            DoctorID = 7,
                            Name = "Terence"
                        },
                        new
                        {
                            ID = 6,
                            DoctorID = 1,
                            Name = "Roosevelt"
                        },
                        new
                        {
                            ID = 7,
                            DoctorID = 9,
                            Name = "Eduardo"
                        },
                        new
                        {
                            ID = 8,
                            DoctorID = 8,
                            Name = "Wilbert"
                        },
                        new
                        {
                            ID = 9,
                            DoctorID = 5,
                            Name = "Tasha"
                        },
                        new
                        {
                            ID = 10,
                            DoctorID = 1,
                            Name = "Max"
                        },
                        new
                        {
                            ID = 11,
                            DoctorID = 2,
                            Name = "BrIDget"
                        },
                        new
                        {
                            ID = 12,
                            DoctorID = 8,
                            Name = "Juan"
                        },
                        new
                        {
                            ID = 13,
                            DoctorID = 10,
                            Name = "Krystal"
                        },
                        new
                        {
                            ID = 14,
                            DoctorID = 10,
                            Name = "Erma"
                        },
                        new
                        {
                            ID = 15,
                            DoctorID = 6,
                            Name = "Orlando"
                        },
                        new
                        {
                            ID = 16,
                            DoctorID = 5,
                            Name = "Marvin"
                        },
                        new
                        {
                            ID = 17,
                            DoctorID = 4,
                            Name = "Lamar"
                        },
                        new
                        {
                            ID = 18,
                            DoctorID = 7,
                            Name = "Joe"
                        },
                        new
                        {
                            ID = 19,
                            DoctorID = 8,
                            Name = "Wendell"
                        },
                        new
                        {
                            ID = 20,
                            DoctorID = 4,
                            Name = "Sandra"
                        },
                        new
                        {
                            ID = 21,
                            DoctorID = 6,
                            Name = "Stephanie"
                        },
                        new
                        {
                            ID = 22,
                            DoctorID = 7,
                            Name = "Ervin"
                        },
                        new
                        {
                            ID = 23,
                            DoctorID = 4,
                            Name = "Beth"
                        },
                        new
                        {
                            ID = 24,
                            DoctorID = 7,
                            Name = "Gretchen"
                        },
                        new
                        {
                            ID = 25,
                            DoctorID = 2,
                            Name = "Gwendolyn"
                        },
                        new
                        {
                            ID = 26,
                            DoctorID = 7,
                            Name = "Jerry"
                        },
                        new
                        {
                            ID = 27,
                            DoctorID = 6,
                            Name = "Mitchell"
                        },
                        new
                        {
                            ID = 28,
                            DoctorID = 8,
                            Name = "Maggie"
                        },
                        new
                        {
                            ID = 29,
                            DoctorID = 3,
                            Name = "Sandy"
                        },
                        new
                        {
                            ID = 30,
                            DoctorID = 2,
                            Name = "Lloyd"
                        });
                });

            modelBuilder.Entity("DiseasePatient", b =>
                {
                    b.HasOne("WebAPIs.Hospital.CleanCrud.DAL.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseasesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPIs.Hospital.CleanCrud.DAL.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAPIs.Hospital.CleanCrud.DAL.Patient", b =>
                {
                    b.HasOne("WebAPIs.Hospital.CleanCrud.DAL.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("WebAPIs.Hospital.CleanCrud.DAL.Doctor", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
